// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeRM2VqRCu-XL7dGxkOn1kye2JhcNFt7k',
    appId: '1:451451856056:web:ea56e7f7e04b844da8c04d',
    messagingSenderId: '451451856056',
    projectId: 'reqres-api-bloc',
    authDomain: 'reqres-api-bloc.firebaseapp.com',
    storageBucket: 'reqres-api-bloc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV9g2Dkn2_3l-au3sXEEk5NvlDWPJdnkE',
    appId: '1:451451856056:android:4d04afa27e2521dba8c04d',
    messagingSenderId: '451451856056',
    projectId: 'reqres-api-bloc',
    storageBucket: 'reqres-api-bloc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjFfGsZOjERAm2FxSZC5j2KgD3z74wLho',
    appId: '1:451451856056:ios:3b7ae75fe2dc1552a8c04d',
    messagingSenderId: '451451856056',
    projectId: 'reqres-api-bloc',
    storageBucket: 'reqres-api-bloc.appspot.com',
    iosBundleId: 'com.example.blocApiCallDemo',
  );
}
